### ISSUE TITLE
KeyError: 'image'

### ISSUE THREAD

**Issue by CandelaAr1992** [schissmantics/yolo-tf2#31]
Hi, I´m trying to reproduce this code with some images from lego and I got and error in the training part.
![image](https://user-images.githubusercontent.com/84021918/125872592-cdf30b33-8e9d-46ea-a196-df00454f76bd.png)

Can you help me?

**Comment by emadboctorx** [comment]
You are getting this error because the csv file containing the relative labels should have the columns indicated in the [docstrings](https://github.com/emadboctorx/yolo-tf2/blob/051457dd22653c5bad3e40db6dc652d5fccc21bb/yolo_tf2/utils/annotation_parsers.py#L140). You need to ensure it has the required columns, which should solve the issue.

**Comment by CandelaAr1992** [comment]
Hi, I´m using a .txt as shows the example not a .csv. Do ro recommend me to use csv file?

**Comment by emadboctorx** [comment]
You should use a csv containing the required columns.

**Comment by schissmantics** [comment]
Closing stale issue
